general:
  use_uvloop: true


functions:
   # Add a tool to search wikipedia
   wikipedia_search:
      _type: wiki_search
      max_results: 2
   rag_post:
      _type: rag_post
      timeout: 60
      url: https://rag-server-x8vcu248o.brevlab.com/v1/generate
      #collection_name: nvidia_report
      collection_name: FarmAnimals
   nvidiallm_service:
      _type: nvidiallm_service
      llm_name: nim_llm
      api_key: "nvapi-*"
      verbose: true
   web_search:
      _type: web_search
      api_key: "tvly-*"
      max_results: 5
      search_depth: "basic"
      verbose: true

llms:
   # Tell AIQ Toolkit which LLM to use for the agent
   nim_llm:
      _type: nim
      model_name: meta/llama-3.3-70b-instruct
      temperature: 0.0
  

workflow:
   # Use an agent that 'reasons' and 'acts'
   _type: react_agent
   tool_names: [wikipedia_search, rag_post, nvidiallm_service, web_search]
   llm_name: nim_llm
   verbose: true
   retry_parsing_errors: true
   max_retries: 3
